import type { Metadata, Viewport } from 'next';
import Script from 'next/script';

import 'tailwindcss/tailwind.css';
/* Core CSS required for Ionic components to work properly */
import '@ionic/react/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/react/css/normalize.css';
import '@ionic/react/css/structure.css';
import '@ionic/react/css/typography.css';

/* Optional CSS utils that can be commented out */
import '@ionic/react/css/padding.css';
import '@ionic/react/css/float-elements.css';
import '@ionic/react/css/text-alignment.css';
import '@ionic/react/css/text-transformation.css';
import '@ionic/react/css/flex-utils.css';
import '@ionic/react/css/display.css';

import '../styles/global.css';
import '../styles/variables.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * initialScale: 1：指定了视口的初始缩放比例为 1。这表示页面在加载时将以原始比例显示，不进行任何缩放。
 * width: 'device-width'：指定了视口的宽度为设备的宽度。这意味着页面的宽度将根据设备的屏幕宽度进行自适应，以确保页面内容在不同设备上显示的一致性。
 * viewportFit: 'cover'：指定了视口的适应模式为覆盖（cover）。这意味着页面的内容将根据视口的宽高比例进行缩放，以确保整个视口被填满，且不会发生变形。这通常用于确保移动设备上的网页内容在屏幕上完整显示，且保持良好的视觉效果。
 */
export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
  viewportFit: 'cover',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
      {/* 两个用于加载Ionicons的JS */}
      <Script
        type="module"
        src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.esm.js"
        strategy="lazyOnload"
      />
      <Script
        noModule
        src="https://unpkg.com/ionicons@5.2.3/dist/ionicons/ionicons.js"
        strategy="lazyOnload"
      />
    </html>
  );
}
